name: KernelSU-Pixel4XL Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # 浅克隆，只获取最新的一次提交

      # 2. 设置编译环境
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Initialization Environment(安装依赖环境)
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # Update package lists
          sudo -E apt -yqq update
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
      
          # Install common dependencies
          sudo -E apt -yqq install dos2unix libfuse-dev wget curl
      
          # Install clang, repo, android tools
          sudo -E apt-get install -y clang-15 python3 python3-pip android-tools-adb android-tools-fastboot git make gcc
      
          # Remove problematic PPA if it's added
          sudo -E add-apt-repository --remove ppa:deadsnakes/ppa
      
          # Set timezone
          sudo -E timedatectl set-timezone "Asia/Shanghai"
      
          # Export the build path as an environment variable
          echo "BUILD_PATH=$PWD" >> $GITHUB_ENV

      - name: Install repo tool
        run: |
          # Download and install the repo tool
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
      
      - name: Initialize and sync Android source
        run: |
          mkdir -p ~/android
          cd ~/android
          repo init -u https://android.googlesource.com/platform/manifest -b android-13.0.0_r29
          repo sync -j$(nproc)  # Shallow clone
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/21.0.6-7/x64
          JAVA_HOME_21_X64: /opt/hostedtoolcache/Java_Zulu_jdk/21.0.6-7/x64
          BUILD_PATH: /home/runner/work/KernelSU-Pixel4XL/KernelSU-Pixel4XL



      # 4. 下载 Android 源代码（使用浅克隆）
      - name: Download Android source code
        run: |
          mkdir -p ~/android
          cd ~/android
          repo init -u https://android.googlesource.com/platform/manifest -b android-13.0.0_r29
          repo sync -j$(nproc)  # Shallow clone

      # 5. 克隆 KernelSU-Pixel4XL 仓库（使用浅克隆）
      - name: Clone KernelSU-Pixel4XL repository
        run: |
          cd ~/android
          git clone --depth 1 https://github.com/msnx/KernelSU-Pixel4XL.git
          cd KernelSU-Pixel4XL

      # 6. 配置编译环境
      - name: Set up environment variables for kernel compilation
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-android-

      # 7. 编译内核
      - name: Build Kernel
        run: |
          cd ~/android/KernelSU-Pixel4XL
          make -j$(nproc) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- kernel_defconfig
          make -j$(nproc) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-android-

      # 8. 上传内核镜像作为构建产物 (使用 curl 直接上传到 GitHub)
      - name: Upload Kernel Image to GitHub Release
        run: |
          # 获取 GitHub 仓库信息
          latest_version=$(date +'%Y%m%d%H%M%S')  # 使用时间戳作为版本号
          
          # 使用 GitHub API 创建一个新的 Release
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"tag_name\": \"v${latest_version}\", \"name\": \"KernelSU-Pixel4XL Build v${latest_version}\", \"body\": \"Automated build for Pixel 4 XL with KernelSU.\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases

          # 获取上传的 Release ID
          release_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/v${latest_version} | jq -r .id)
          
          # 上传文件
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @~/android/KernelSU-Pixel4XL/out/arch/arm64/boot/Image \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${release_id}/assets?name=Image"
