name: KernelSU-Pixel4XL Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        
      # 2. 设置编译环境
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'openjdk'  # 使用 openjdk

      # 3. 安装依赖
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            make \
            gcc \
            clang \
            repo \
            python3 \
            python3-pip \
            android-tools-fastboot \
            android-tools-adb \
            curl

      # 4. 下载 Android 源代码
      - name: Download Android source code
        run: |
          mkdir -p ~/android
          cd ~/android
          repo init -u https://android.googlesource.com/platform/manifest -b android-13.0.0_r25
          repo sync -j$(nproc)

      # 5. 克隆 KernelSU-Pixel4XL 仓库
      - name: Clone KernelSU-Pixel4XL repository
        run: |
          cd ~/android
          git clone https://github.com/msnx/KernelSU-Pixel4XL.git
          cd KernelSU-Pixel4XL

      # 6. 配置编译环境
      - name: Set up environment variables for kernel compilation
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-android-

      # 7. 编译内核
      - name: Build Kernel
        run: |
          cd ~/android/KernelSU-Pixel4XL
          make -j$(nproc) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- kernel_defconfig
          make -j$(nproc) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-android-

      # 8. 上传内核镜像作为构建产物 (使用 curl 直接上传到 GitHub)
      - name: Upload Kernel Image to GitHub Release
        run: |
          # 获取 GitHub 仓库信息
          latest_version=$(date +'%Y%m%d%H%M%S')  # 使用时间戳作为版本号
          
          # 使用 GitHub API 创建一个新的 Release
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"tag_name\": \"v${latest_version}\", \"name\": \"KernelSU-Pixel4XL Build v${latest_version}\", \"body\": \"Automated build for Pixel 4 XL with KernelSU.\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases

          # 获取上传的 Release ID
          release_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/v${latest_version} | jq -r .id)
          
          # 上传文件
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @~/android/KernelSU-Pixel4XL/out/arch/arm64/boot/Image \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${release_id}/assets?name=Image"
